### ISSUE TITLE
Clock Keeps Resetting

### ISSUE THREAD

**Issue by BobsUncle** [copperhead/bugtracker#552] opened 2016-12-30 12:59 UTC
Successfully flashed Nexus5x

Purchased 6P.

Flashed. After every reboot the clock resets back to year 1971.

**Comment by thestinger** [comment] 2016-12-30 13:48
On which device?

**Comment by BobsUncle** [comment] 2016-12-30 19:51
brand new Nexus 6P

**Comment by thestinger** [comment] 2016-12-30 23:01
Can you try with stock Android?

**Comment by thestinger** [comment] 2016-12-30 23:02
Also, best to try without it having a SIM card / network access to make sure it's not simply updating the time itself. As in set proper time, reboot, without it having a way to get it if it gets reset.

**Comment by BobsUncle** [comment] 2016-12-30 23:15
Reflashed to stock. Clock works fine all normal. 

No sim card has been used in this phone period so that can't be the cause.

I will now try to reflash the 6P to copperhead see what happens.

**Comment by BobsUncle** [comment] 2016-12-31 00:06
The problem still persists. Just to do a recap:

Fresh Nexus 6P unlocked. Clocks reset to 1971 after every reboot. Followed instructions exact same process as Nexus 5X which I worked successfully. Problem persists so I refreshed stock android. The clock was working fine under stock android. So I re flashed back to copper head re downloaded all files and did it fresh. Problem persists.

**Comment by BobsUncle** [comment] 2016-12-31 04:06
Please someone suggest something I might be able to do to fix this

**Comment by zongo** [comment] 2016-12-31 04:20
Make sure all update are done on stock. Then flash.have a brand new 6P and have been using copperheadOS as my daily driver for the past month with no issue at all. Clock resetting sounds more hardware related though

**Comment by BobsUncle** [comment] 2016-12-31 05:50
but it only happens on copperhead works fine in stock android

**Comment by canary5** [comment] 2016-12-31 07:48
I can confirm this issue

**Comment by thestinger** [comment] 2016-12-31 13:24
@zongo You don't need to do stock updates before flashing CopperheadOS. Nothing remains from the stock images after flashing CopperheadOS. It flashes / updates the low-level firmware too.

**Comment by thestinger** [comment] 2016-12-31 13:38
Can't reproduce this so someone with the problem will need to debug it. At the very least, logs will be required, but that's probably not going to provide the information required to fix the problem.

**Comment by BobsUncle** [comment] 2016-12-31 19:58
Solved!

I nexus I purchased was brand new. After I put a non-activated SIM card in the problem resolved itself and now the clock works even after reboot.

So perhaps, put a note somewhere for anyone else like myself who goes and buys a new Nexus 6P phone to setup copperhead that they should insert a SIM card to make sure the hardware clock gets proper sync. The SIM card does not need to be activated.

Thank you community for support.

**Comment by BobsUncle** [comment] 2016-12-31 20:23
OK, I just noticed if I reboot the Nexus 6P in airplane mode the internal clock resets back to 1971.

**Comment by thestinger** [comment] 2017-01-15 05:46
> So perhaps, put a note somewhere for anyone else like myself who goes and buys a new Nexus 6P phone to setup copperhead that they should insert a SIM card to make sure the hardware clock gets proper sync. The SIM card does not need to be activated.

I thought I made it clear, but this isn't a normal issue. It isn't something that everyone is experiencing, only a few people, and none of them bought phones from us where we know the OS is flashed properly.

**Comment by thestinger** [comment] 2017-01-15 05:49
This doesn't appear to be a CopperheadOS issue since there are many reports about this upstream and it can't be reproduced here. The reason you're getting inconsistent results is likely inconsistent testing.

**Comment by canary5** [comment] 2017-01-18 10:13
I did clean install. Edited time settings settings. Rebooted. And it was reset. Heres the log.
pastebin.com/QmNG6rQe

**Comment by thestinger** [comment] 2017-01-30 04:26
Are you using airplane mode?

**Comment by canary5** [comment] 2017-01-30 04:44
Yes

**Comment by thestinger** [comment] 2017-01-30 04:56
Check what happens with WiFi disabled, no SIM card inserted but airplane mode not enabled.

**Comment by canary5** [comment] 2017-01-30 08:23
Still same, the clock was resetted

**Comment by e-lektryk** [comment] 2017-02-05 13:34
I think I have just seen simillar issue on my Nexus 6p. Today 05.02.2017 aproximatelly at 9 have installed February update. Just after phone restart, it showed date 04.02.2017, time aproximatelly at 22. Correct time was displayed after I entered pin for SIM card (and synchronise with network). I have a feeling that "last known time" is stored somewhere in the system and restored on phone restart, however it is updated only in some specific condition.

**Comment by ubestemt** [comment] 2017-02-17 15:09
My Nexus 6P also has this bug. I have used it with a SIM card, but in airplane mode. Whenever I restart the phone, the clock gets reset (to 1971). I ran some simple tests:

1. flight mode enabled, "automatic time & date" enabled: Clock gets reset.
2. flight mode enabled, "automatic time & date" disabled: Clock gets reset.
3. flight mode disabled, "automatic time & date" enabled: Clock gets set correctly.
4. flight mode disabled, "automatic time & date" disabled: Clock gets reset.

Then I removed the SIM card and repeated test 1 and 3...and got the same results. (I didn't keep track of when wifi was enabled, but it has always been enabled before when the clock has been reset before.)

Whenever I disabled flight mode and enabled automatic time & date, the clock would be set correctly. 

So it seems that the clock gets reset on every boot and the network-provided time is needed to set the clock again.

**Comment by thestinger** [comment] 2017-02-17 20:03
The symptoms are understood at this point, not the cause. All that's needed is for someone able to reproduce this to debug the cause so it can be fixed.

**Comment by kittenpirate** [comment] 2017-03-08 01:35
I have the same problem with my Nexus 6P whenever I use it in airplane mode with CopperheadOS.

**Comment by thestinger** [comment] 2017-03-09 18:46
As I said the symptoms are well understood, this only requires someone to work on it.

**Comment by thestinger** [comment] 2017-04-08 02:35
Closing in favour of #616 which can actually be reproduced.

**Closed by thestinger** 2017-04-08 02:35 UTC
Labels: bug, upstream
