### ISSUE TITLE
Cell Standby drains battery when in Airplane Mode (wifi enabled)

### ISSUE THREAD

**Issue by zmcNTP4fM9Kg** [copperhead/bugtracker#347] opened 2016-07-20 01:29 UTC
I have a Nexus 6P that I flashed to the Copperhead OS, when I heard it became available. So far, I've been very pleased with it - great work! I've encountered one annoying issue where my battery will drain at least 50% per day and attribute it to Cell Standby in the Android battery monitor app. I only encounter this issue when I place my phone in Airplane mode. When the battery is draining, I have excellent wifi reception. 

Cell Standby (random sample from today, 23% used so far)
Time without a signal: 0%
Mobile radio active: 4h 14m 52s
Computed Power Use: 782 mAh

This issue reminds me of the similar Android 5.02 issue: https://code.google.com/p/android/issues/detail?id=170697

**Comment by GarrettGotu** [comment] 2016-07-20 02:16
As per my other bugtracker submission yesterday, I'm getting very similar issues.
I thought it was related to LibreSignal, using websockets, but it wasn't.
Will be happy to provide logcat dump.

I only get this issue when wifi is enabled (Connected or not, still causes this issue)

I've reflashed 3 times now, happens after the first reboot regardless of what apps you have installed (I got it with none or some additional)

**Comment by thestinger** [comment] 2016-07-20 02:18
Probably not related to CopperheadOS features but rather is an issue in AOSP. I have a few ideas about things that are different from stock though, so might get fixed in some upcoming changes. Same potential cause as #344.

**Comment by thestinger** [comment] 2016-07-20 02:18
AOSP is missing a build feature which seems to lead to some power saving related code not being included on the 5X and 6P. Remains to be seen if it makes any difference though.

**Comment by zmcNTP4fM9Kg** [comment] 2016-07-20 18:56
Thanks for taking a look at this, I know this must be a labor of love and I appreciate your efforts. I'll keep tweaking settings to see if I can find anything useful to the community.

Minor note - I think thestinger meant to reference this bug https://github.com/copperhead/bugtracker/issues/346, adding a note. Apologies if I'm mistaken.

**Comment by thestinger** [comment] 2016-07-21 00:35
No I meant #344.

**Comment by thestinger** [comment] 2016-07-21 00:41
As I've said elsewhere, I highly doubt that issues like this are caused by any CopperheadOS features. I don't want to run a tracker for all issues in AOSP. Google already has one. There's now a workaround for yet another AOSP bug that's not present in stock (https://github.com/CopperheadOS/platform_build/commit/600d75d206caf20576880842d90bf5e40db0eb8) but it's unlikely it's related to this. If you want to fix AOSP issues, you need to tell me the fix as #344 did rather than the symptom.

**Closed by thestinger** 2016-07-21 00:41 UTC
Labels: bug, Nexus 5X, Nexus 6P, upstream

**Comment by thestinger** [comment] 2016-07-21 00:43
It may also be a bug that's also present in stock, or not a bug at all. High power usage is completely normal if you have poor reception.

**Comment by thestinger** [comment] 2016-07-21 00:49
Here's an example of power saving code that wasn't being used, but is now enabled with #344 fixed: https://android.googlesource.com/device/lge/bullhead/+/android-6.0.1_r54/power/power-8994.c. None is directly related to cell standby AFAICT, but it's possible that *something* changed. Next release will have these assorted hardware tweaks that were supposed to be there but AOSP didn't have the code to enable them.

**Comment by Rudd-O** [comment] 2016-07-24 16:36
That is real fishy.  The radio should NOT be on — that's the whole point of Airplane Mode.

**Comment by thestinger** [comment] 2016-07-24 22:50
The power statistics aren't necessarily accurate. Either way, this isn't a CopperheadOS issue making it out-of-scope for this bug tracker.
