### ISSUE TITLE
No pin unlock needed to turn on wifi/bt.

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#546] opened 2016-12-27 22:39 UTC
I just was supprised, that even if phone is locked by PIN, anyone can turn on wifi or bluetooth and possible extend surface of attack on the phone.

**Comment by thestinger** [comment] 2016-12-28 08:59
Duplicate of https://github.com/copperhead/bugtracker/issues/460.

**Closed by thestinger** 2016-12-28 08:59 UTC
