### ISSUE TITLE
Noise freezes on Nexus 6P after update N2G48B.2017.07.06.00.04.39

### ISSUE THREAD

**Issue by Caesarwm1** [copperhead/bugtracker#660] opened 2017-07-06 22:13 UTC
Hello.

After tapping a contact in order to view the conversation, Noise just shows a blank white screen.
I'm able to escape by pressing the home button.

I sent the output of adb logcat during this sequence as thestinger described in issue #657 via email.

»Pure« Copperhead OS, no issues before this one.
 Silence is working fine.

Best, 
R.

**Comment by thestinger** [comment] 2017-07-06 22:17
On which device?

**Comment by Caesarwm1** [comment] 2017-07-06 22:18
Daniel Micay:
> On which device?
> 
Nexus 6p (not in Subject?)

**Comment by thestinger** [comment] 2017-07-06 22:18
Yeah, I saw that after.

**Comment by thestinger** [comment] 2017-07-06 22:20
Check if it has the Phone permission in Settings -> Apps -> Noise -> Permissions. If not, toggle it on. If it does have it already, try toggling it off, leaving that page, and going back there to toggle it on again.

**Comment by Caesarwm1** [comment] 2017-07-06 22:26
Daniel Micay:
>  If it does have it already, try toggling it off, leaving that page, and going back there to toggle it on again.
> 
Leaving that page and coming back toggles it on again automatically.
Anyway: no changes in Noise' behaviour.

**Comment by thestinger** [comment] 2017-07-06 22:46
Please upgrade to N2G48B.2017.07.06.18.26.24 and try there.

**Comment by thestinger** [comment] 2017-07-06 22:57
I'm not sure why this is happening, but I don't think it's directly related to any of the recent OS changes. I think it might be an earlier issue uncovered by upgrading. Downgrading Noise and then upgrading it again *might* work around it, although it could happen again without identifying the cause.

**Comment by Caesarwm1** [comment] 2017-07-06 23:01
Okay, thank you.
No luck after the update.

**Comment by Caesarwm1** [comment] 2017-07-06 23:41
> Downgrading Noise and then upgrading it again *might* work around it.

Yes, thanks again, seems to be a workaround, for now.

**Comment by thestinger** [comment] 2017-07-07 02:44
Closing for now because I don't think this is a CopperheadOS issue but rather a Noise issue. Can reopen it if it happens again.

**Closed by thestinger** 2017-07-07 02:44 UTC
Labels: bug

**Comment by Caesarwm1** [comment] 2017-08-11 19:58
Hello.

Same (mis)behavior as in my first post here, now after update to N2.G48C.2017.08.07.22.43.31.
Just reporting 

(I never managed just downgrading and upgrading via F-Droid – "error-25". The other ways really are annoying. But, okay, no problem.)

Best regards.
