### ISSUE TITLE
OS not starting after last update

### ISSUE THREAD

**Issue by jo3l33** [copperhead/bugtracker#424] opened 2016-09-09 09:55 UTC
Hi, 
after last update OS starts (on nexus 5x) till passphrase entry then check it and then display spinning logo forever. OS does not load. I have tried to sideload latest update via adb - same result. 

What may I try to get it working ? Or should I waste time with complete factory reset & losing all my data ?

Thanks in advance for reply&help.

**Comment by jo3l33** [comment] 2016-09-09 11:13
Ok, so I am unable to fastboot oem unlock via adb (FAILED: remote: oem unlock is not allowed) ? How may I restore to factory if I am not able to unlock bootloader ? I can't obviously allow oem unlock in dev option because OS is not starting. 
Any solution for this ?
Thanks.

**Comment by jo3l33** [comment] 2016-09-09 11:49
Will reflash of https://builds.copperhead.co/builds/bullhead-factory-2016.09.09.07.12.48.tar.xz work without unlocking bootloader ? Should be possible - signed by same key I presume ?
Thanks for help&info.

**Comment by jo3l33** [comment] 2016-09-09 12:06
Ok, so it can't be done - Cooperhead original factory img can not be reflashed. Bootloader locked. 

I am out of options I know of. Devs of Copperhead, please let me know if there is any way of repairing it. Thanks.

**Comment by thestinger** [comment] 2016-09-10 03:16
If you locked the bootloader and then disabled OEM unlocking, there is no way to unlock the bootloader without booting into the OS. You can sideload updates, so if this is caused by a bug occurring then it could be fixed by an update. It's feasible that it's a hardware issue or an issue like data corruption which would not be fixable by a normal update. If it's data corruption, in the worst case scenario we could produce a sideload package to format the device. However, there are there drastic measures that could be taken before that.

More information would be helpful, i.e. whether this is an unaltered install of CopperheadOS (no unofficial sideloaded modifications) and more details on what led up to this situation.

Did the update process appear to complete without interruption?

Does it state that the installation is corrupted or boot, or does it produce the normal yellow state for a third party OS with the correct key fingerprint?

**Comment by thestinger** [comment] 2016-09-10 03:17
I could make you a userdebug build where you would have `adb` access in early boot to obtain logs and perhaps fix the problem.

**Comment by thestinger** [comment] 2016-09-10 03:21
> after last update OS starts (on nexus 5x) till passphrase entry then check it and then display spinning logo forever

Does it make it far enough for you to enter your password? It's not clear to me if the boot stalls before it gets there, or after you enter it.

**Comment by thestinger** [comment] 2016-09-10 03:21
It sounds like it stalls after, in which case you might already have adb access if you had it enabled and a key was already whitelisted (userdebug builds simply have it force enabled including in early boot and do not require authentication, which is why that would help).

**Comment by jo3l33** [comment] 2016-09-11 16:04
Hi thestinger, 
thank you very much for your reply&help. 

I have unaltered install of CopperheadOS (no unofficial sideloaded modifications) and I can see  normal yellow state for a third party OS with the correct key fingerprint after boot. After boot OS starts to load - spining Copperhead logo, then it asks for passphrase to unlock OS. I can normally enter passphrase and it apparently checks it, if it is correct (if I enter wrong one, it prompts about wrong passphrase). 
Once it checks passphrase it starts to load OS with spinning logo once again after which nothing happens - I tried to let it run for couple of hours and it is still spinning - no OS loaded. 

I can sideload via recovery option in bootloader. I have usb driver and adb/fastboot tools set up. I have vanilla copperhead OS so no modifications. Just have all security options maxed. Phone is like 4 months old (bought new). I've choosen this phone, because I wanted to use your Copperhead OS. 

Let me please know, what I can try - either sideload some debug img you will provide or anytning else you recommend. I was thinking about waiting for your next release and would try to sideload it (it wont let me sideload previous updates before this last one). 

Thank you very much for any help.

**Comment by jo3l33** [comment] 2016-09-11 16:13
Edit* - yes, update process went smoothly - no problem there. Then it restarted and started loading OS as I have described above. Thanks.

**Comment by thestinger** [comment] 2016-09-11 20:21
Did you have adb enabled already? You should still have adb access after you enter the passphrase via the same previously whitelisted computer if you did.

**Comment by jo3l33** [comment] 2016-09-11 20:29
I should have adb access (computer whitelisted a while ago, but usb debug was switched off). 
What command should I send via adb ? Thanks for help.

**Comment by thestinger** [comment] 2016-09-11 21:30
If you do still have adb access, get the logs with `adb logcat`. If not, I can upload a userdebug build to sideload.

**Comment by jo3l33** [comment] 2016-09-12 07:56
adb logcat - no response (- waiting for device -) - so I guess I do not have adb access afterall. But I can sideload via recovery option in bootloader. Thank you for all your help.

**Comment by thestinger** [comment] 2016-09-12 08:00
A userdebug build would give you adb access, but it doesn't really work as a non-local solution. Publishing it would reduce security for all CopperheadOS users...

**Comment by thestinger** [comment] 2016-09-12 08:01
I'll try to think of a way to deal with this. I don't know though.

**Comment by thestinger** [comment] 2016-09-12 08:31
Could create a user build with the ability to wipe from recovery, which would only compromise the anti-theft value of OEM unlocking (not a big deal). That wouldn't allow for data recovery or determining what went wrong though.

**Comment by jo3l33** [comment] 2016-09-12 09:43
Thank you very much for further info! I certainly do not want you to compromise any of security features of Copperhead OS for other users. Though I would like to know, what caused this, but if there is only solution to wipe from recovery I do not leave any critical data on my phone/s anyway - so I can part with my existing data there. 
If there is solution that I can wipe data and load full latest Copperhead img, that would be best solution from my side. Also, if you do not want to publish custom "wipe" build, I can assure you, that if you send it to me, I will use it and delete it. I understand the the value you are creating with secured custom OS and that is why I am using it/bought phone supporting it. 
Thank you again for your help.

**Comment by thestinger** [comment] 2016-09-12 09:46
I wouldn't really mind publishing it since it's just an anti-theft feature but sending a link to you via email would be saner. Note that since downgrades aren't be possible, it becomes irrelevant after the next update anyway (since it can no longer be used to wipe updated installs).

**Comment by thestinger** [comment] 2016-09-12 09:46
Would really like to find out what the problem is and fix it, but I can't think of a sane way to do that.

**Comment by jo3l33** [comment] 2016-09-12 10:37
Hi Daniel, I've sent you an email with further info. Thank you very much for all your help. Joe.

**Comment by thestinger** [comment] 2016-09-14 12:44
(not going to be further progress on identifying the cause since the wipe approach was taken)

**Closed** 2016-09-14 12:44 UTC
Labels: bug
