### ISSUE TITLE
Nexus 5 Wifi Issue

### ISSUE THREAD

**Issue by Lloir** [copperhead/bugtracker#134] opened 2016-01-03 21:58 UTC
In a nut shell

Enable WiFi
Turn phone screen off
Check after 20~mins (Maybe less maybe more)
WiFi isn't connected.
WIFI reconnects once the screen is turned on.

Checked Settings > WiFi > Advanced > Keep WI-FI on during sleep, set to ALWAYS

Happens with multiple routers
Happens on 2.4ghz and 5ghz and Automatic

I'll throw some logs in when I get time.

**Comment by polyzen** [comment] 2016-01-03 23:23
Happens here as well. It's a pain considering I often use it while
tethering :p

**Comment by thestinger** [comment] 2016-01-04 03:46
Can you try enabling stay awake in developer settings and seeing if it disconnects?

**Comment by thestinger** [comment] 2016-01-04 12:49
I don't really think this is caused by CopperheadOS and I'm also unable to reproduce the problem. You would probably have the same issue with AOSP.

**Comment by thestinger** [comment] 2016-01-04 12:50
A quick search finds plenty of people with the same issue on the stock OS. I can't approach it until it's both known to be caused by CopperheadOS and can be reproduced.

**Comment by Lloir** [comment] 2016-01-04 16:27
@thestinger you're probably right it being an AOSP issue.
I'll see if I can fix it and push a patch to you and to AOSP.

Though I'm assuming you tried using with the Nexus 5, what is your router set to? (2.4/5) As I'm wondering if it's that causing the issue.

**Comment by polyzen** [comment] 2016-01-04 17:08
Only tried on 5GHz, here.

**Comment by thestinger** [comment] 2016-01-04 17:47
If it caused a kernel panic, my assumption would be a PaX REFCOUNT issue. But I can't think of anything that would cause it to simply drop off in CopperheadOS specifically and there seem to be lots of people having the issue on the Nexus 5 elsewhere.

It doesn't drop off for me with either 2.4 or 5GHz wireless N. The one problem that I run into is that it sometimes takes a while to connect on boot, but I think it does connect without intervention. It happens on AOSP / stock Android too though. Just seems like the radio stuff takes a while to get started in terms of that issue.

**Comment by zokipirlo** [comment] 2016-01-09 17:05
I don't think it's a bug. That's how my Nexus 5 works on stock 6.0.1.

**Comment by thestinger** [comment] 2016-01-09 17:18
Well, it might be a bug, but it's not a CopperheadOS bug.

**Comment by thestinger** [comment] 2016-01-21 23:24
Closing as this is an issue in stock and doesn't appear to be made any worse by CopperheadOS. It makes sense to track upstream issues but only if they're more relevant to CopperheadOS than stock.

**Closed by thestinger** 2016-01-21 23:24 UTC
Labels: bug, Nexus 5, unconfirmed, upstream

**Comment by vanitasvitae** [comment] 2016-04-25 10:11
Afaik this is now fixed in AOSP according to this discussion:
https://code.google.com/p/android/issues/detail?id=190667&can=1&q=stars%3D128&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

Looking forward to the next CopperheadOS release :)

**Comment by thestinger** [comment] 2016-04-25 12:04
The new builds are on another branch, which is a pain to deal with.
