### ISSUE TITLE
SIGSEGV in "am" and "wm" tools when run from adb shell due to exec spawning

### ISSUE THREAD

**Issue by smaeul** [copperhead/bugtracker#190] opened 2016-02-24 05:18 UTC
https://gist.githubusercontent.com/smaeul/87ff4e34e88423f7d4ba/raw/5ec844294f5ff0a948b5af766158fce43c0899ae/adb_shell_am-logcat

https://gist.githubusercontent.com/smaeul/87ff4e34e88423f7d4ba/raw/5ec844294f5ff0a948b5af766158fce43c0899ae/adb_shell_wm_density-logcat

Present in both the 2016.02.18 and 2016.02.21 builds.

**Comment by thestinger** [comment] 2016-02-24 05:23
I've seen that crash before. It's one of the Android bugs uncovered by using exec spawning. I expect you would hit the same issue if you enabled Android's wrap feature (not available outside of userdebug/eng builds though).

**Comment by thestinger** [comment] 2016-06-04 04:06
This only happens on the Nexus 5, as it appears to be caused by PaX changes that are still active when soft mode is enabled. It's probably the changes related to the stack gap.

If it was only relevant to the Nexus 5, I would just close this, but ART should be improved to work with PaX because it's going to be relevant in the future.

**Comment by thestinger** [comment] 2016-06-05 00:59
This is fixed.

**Closed by thestinger** 2016-06-05 00:59 UTC
Labels: bug, Nexus 5, upstream
