### ISSUE TITLE
UI sounds not working

### ISSUE THREAD

**Issue by ziekke** [copperhead/bugtracker#352] opened 2016-07-22 16:15 UTC
I have enabled UI sounds (keyboard, lock, charging) but they don't work. Phone is not silent and they are enabledin settings.

**Comment by thestinger** [comment] 2016-07-23 00:01
I have a feeling that this doesn't work in AOSP. Someone needs to confirm that this is a CopperheadOS issue.

**Comment by ziekke** [comment] 2016-07-23 21:10
Not sure how I can check this but if I could I would!

**Comment by thestinger** [comment] 2016-07-23 21:12
Building AOSP and checking if the problem is there too.

**Comment by Rudd-O** [comment] 2016-07-24 16:30
I can confirm that keyboard sounds in lockscreen and charger connected sounds are not working.  Sounds do work in the Sound & notification preferences panel.

**Comment by Rudd-O** [comment] 2016-07-24 16:30
I am using the very latest build available right now, installed it 30 minutes ago.

**Comment by Rudd-O** [comment] 2016-07-24 16:35
Notification sounds do happen when the phone is locked.

**Comment by thestinger** [comment] 2016-07-24 22:43
It needs to be confirmed that this is a CopperheadOS issue rather than an AOSP issue.

**Comment by AdFad666** [comment] 2016-07-27 19:08
I noticed this too when I build using `marshmallow-dr1.6-release` apparently based on `android-6.0.1_r54`. I've been building AOSP against `android-6.0.1_r46` and previous releases without issue.

I'll try a pure AOSP build with the same tag. FWIW I get this in logcat when I tap the app drawer button on the home screen:

```
07-27 20:40:41.849: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.849: E/SoundPool(891): Unable to load sample
07-27 20:40:41.849: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.850: E/SoundPool(891): Unable to load sample
07-27 20:40:41.850: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.851: E/SoundPool(891): Unable to load sample
07-27 20:40:41.851: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.851: E/SoundPool(891): Unable to load sample
07-27 20:40:41.851: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.851: E/SoundPool(891): Unable to load sample
07-27 20:40:41.851: W/AudioService(891): onLoadSoundEffects(), Error -10000 while loading samples
07-27 20:40:41.852: W/MessageQueue(891): Handler (android.media.SoundPool$EventHandler) {72a6428} sending message to a Handler on a dead thread
07-27 20:40:41.852: W/MessageQueue(891): java.lang.IllegalStateException: Handler (android.media.SoundPool$EventHandler) {72a6428} sending message to a Handler on a dead thread
07-27 20:40:41.852: W/MessageQueue(891): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
07-27 20:40:41.852: W/MessageQueue(891): 	at android.os.Handler.enqueueMessage(Handler.java:631)
07-27 20:40:41.852: W/MessageQueue(891): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
07-27 20:40:41.852: W/MessageQueue(891): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
07-27 20:40:41.852: W/MessageQueue(891): 	at android.os.Handler.sendMessage(Handler.java:507)
07-27 20:40:41.852: W/MessageQueue(891): 	at android.media.SoundPool.postEventFromNative(SoundPool.java:532)
07-27 20:40:41.854: E/NdkMediaExtractor(891): sf error code: -1010
07-27 20:40:41.854: E/SoundPool(891): Unable to load sample
```

**Comment by thestinger** [comment] 2016-09-01 03:59
This is fixed in the nougat-release branch, since it's not a problem upstream there.

**Closed by thestinger** 2016-09-01 03:59 UTC
Labels: bug, priority-low, upstream
