### ISSUE TITLE
Copying text from K9 seems to be broken

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#766] opened 2017-10-12 23:31 UTC
Hi!
When I open a mail in k9, long click the content to select some text and then copy it to the clipboard, the text doesn't actually get copied. The clipboard remains unchanged.

I reported this behavior in the k9 bugtracker, but they told me its an issue with coppherheadOS. Copying text in other parts of the OS seems fine though.

https://github.com/k9mail/k-9/issues/2826

**Comment by thestinger** [comment] 2017-10-12 23:36
No indication that this is an issue with CopperheadOS...

You can turn on background clipboard access in Settings -> Security but note that it's code from Google that we're just actively for other types of apps:

https://github.com/CopperheadOS/platform_frameworks_base/commit/fb710571e8d8fa8fbe8b8b2a07118a5eca6b420d

Eventually, Google will ship this for normal apps too.

**Comment by vanitasvitae** [comment] 2017-10-12 23:38
Just for documentation: enabling background access to clipboard does NOT solve the issue for me.

**Comment by thestinger** [comment] 2017-10-12 23:45
So it's not a compatibility issue tied to CopperheadOS.

**Comment by thestinger** [comment] 2017-10-12 23:49
They closed the issue simply because you stated it occurred on CopperheadOS, not because they have any actual reason to think it's tied to CopperheadOS. This isn't the right place to file a K9 issue. You'll need to replicate the same scenario on stock Android and file it again with them if that's all they want to support. I recommend using `adb backup` and `adb restore` to move the app over to a different device on stock 8.0.0.

**Comment by thestinger** [comment] 2017-10-12 23:58
Also try capturing logs with `adb logcat`, but really, I don't see how it could be tied to CopperheadOS. It's far more likely that you found a way to break it on 8.0.0 in general.

**Comment by xbtc-im** [comment] 2017-10-13 09:29
vanitasvitae what version of k9 mail are you using ? 
i have the same issue, running k9 version v5.300. i also believe this is not a copperhead issue, but k9/oreo related. Same thing when selecting text and trying to "share" it, nothing happens.

**Comment by xbtc-im** [comment] 2017-10-13 09:41
it's related to this bug:
https://github.com/copperhead/bugtracker/issues/644
copy/paste/share issue also happens with Chormium , im guessing k9 uses WebView to display e-mails, so this is an inherited issue. Same with pdf viewer and everything that uses WebView.

**Comment by thestinger** [comment] 2017-10-13 09:47
> Just for documentation: enabling background access to clipboard does NOT solve the issue for me.

**Comment by thestinger** [comment] 2017-10-13 09:48
When that feature denies access to the clipboard, it logs it anyway.

**Comment by xbtc-im** [comment] 2017-10-13 09:53
Same here, it has nothing to do with clipboard access permission. Copy/Paste/Share just doesn't work in Chromium and any WebView related app ...

**Comment by thestinger** [comment] 2017-10-13 16:45
That's not what #644 is filed about and if you're saying it doesn't work with share either that's a much different issue. It isn't something that I've heard about before. It's working for other people.

**Comment by xbtc-im** [comment] 2017-10-13 16:50
I believe it's at lease related. You can copy/paste/share from the "headers" box in k9, similar to copying from the address bar in Chromium ... I might be wrong though, maybe someone else can try too ...

**Comment by xbtc-im** [comment] 2017-10-13 16:50
Can you copy text from PdfViewer ?

**Comment by thestinger** [comment] 2017-10-13 16:52
It's not related if enabling background clipboard access doesn't resolve it. The issue is filed about the background clipboard access feature, not something else.

**Comment by xbtc-im** [comment] 2017-10-13 16:57
Can you copy text from PdfViewer ? Forget the "share" part ... 
And still Chromium/WebView are the only ones that have this problem. k9 uses WebView to display the email content, i remember an older issue an user had after disabling Chromium.

**Comment by thestinger** [comment] 2017-10-13 17:12
Yes, copying test works for me, but the issue makes sense to me now and could be a Chromium bug that will be resolved by v63. v60 and v61 didn't have support for Oreo open sourced and it's in a weird situation right now, although I wouldn't expect that to impact Chromium only the WebView.

**Comment by xbtc-im** [comment] 2017-10-13 17:22
Yes, if i remember correctly, this started since Oreo ...

**Comment by thestinger** [comment] 2017-10-13 18:05
And to clarify something "upstream-app" in this case applies to Chromium.

**Comment by xbtc-im** [comment] 2017-10-13 19:36
Did you test other WebView apps ?

**Comment by vanitasvitae** [comment] 2017-10-13 19:45
Bug does not appear on k9 on LineageOS 15.

**Comment by xbtc-im** [comment] 2017-10-13 19:48
@vanitasvitae can you also test other webview related apps ? Also the "share" option ?

**Comment by xbtc-im** [comment] 2017-10-13 19:55
Probably the bug does not appear on standard AOSP either

**Comment by thestinger** [comment] 2017-10-13 20:01
> as far as i know, Lineage uses their own version of Browser/WebView ...

No, they use Google's WebView build. I explained this already:

> Yes, copying test works for me, but the issue makes sense to me now and could be a Chromium bug that will be resolved by v63. v60 and v61 didn't have support for Oreo open sourced and it's in a weird situation right now, although I wouldn't expect that to impact Chromium only the WebView.

and

> And to clarify something "upstream-app" in this case applies to Chromium.

**Comment by thestinger** [comment] 2017-10-13 20:02
@xbtc-im AOSP doesn't have a current release of the WebView. It has a build of Chromium v58 from their internal tree with code that wasn't open sourced:

https://android.googlesource.com/platform/external/chromium-webview/+log/daaab59ab71941fbdbeb0403f01e851bb2ff56c8

**Comment by xbtc-im** [comment] 2017-10-13 20:13
Thanks for the clarification. Basically we should wait for the next Chromium release , right ?

**Comment by xbtc-im** [comment] 2017-10-13 20:18
Anyway comparing CopperheadOS, AOSP, Lineage, etc, is like apples and oranges problem... They all have their goods and bads.
So this issue is Chromium related after all ...

**Comment by thestinger** [comment] 2017-10-13 20:26
I stated that it's likely an issue with Chromium caused by the code not being fully open sourced. I said that above before this discussion. I didn't say I was certain that was the issue.

Anyway, I'm not finding this thread to be useful.

**Closed by thestinger** 2017-10-13 20:26 UTC
Labels: Component: Chromium, Type: bug, upstream-app

**Comment by thestinger** [comment] 2017-10-13 20:29
https://github.com/copperhead/bugtracker/issues/767 is the new issue tracking this problem. This thread isn't productive.

**Comment by thestinger** [comment] 2017-10-21 19:05
This is fixed in Chromium 62 which is in the latest CopperheadOS release for today.

**Comment by vanitasvitae** [comment] 2017-10-21 20:45
I can conform that the issue is resolved. Great :)

**Comment by thestinger** [comment] 2017-10-21 20:48
It was probably caused by Google's botched release of the Chromium sources. v60 and v61 didn't have full Oreo support and we had to deal with that downstream, which apparently wasn't complete.
