### ISSUE TITLE
Chromium crashes on "Stop using invalid certificate" on N5

### ISSUE THREAD

**Issue by reenz0h** [copperhead/bugtracker#233] opened 2016-04-09 20:15 UTC
I'm not sure if it's somewhat related to this: https://github.com/copperhead/bugtracker/issues/229 but I've noticed that Chromium crashes when "Stop using invalid certificate" is chosen from certificate/connection details.

Testing procedure:
1. open https://ixquick.com in Incognito mode
2. select "Lock" in address bar
3. Select "Details"
4. Select "Stop using an invalid certificate"

Phone model: **Nexus 5**
Build number: **MMB29X.2016.04.05.04.42.49**
Security level set: **middle** (no additional sec features turned on)
Language: **English**
**Logcat**:
```
--------- beginning of system
04-09 21:57:44.318  1978  2165 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 106] to 52
--------- beginning of main
04-09 21:57:44.630 10862 10862 D QSEECOMD: : qseecom listener services process entry PPID = 1
04-09 21:57:44.630 10862 10862 E QSEECOMD: : Listener: index = 0, hierarchy = 0
04-09 21:57:44.630 10862 10862 E QSEECOMD: : Init dlopen(librpmb.so, RLTD_NOW) is failed....
04-09 21:57:44.630 10862 10862 E QSEECOMD: : ERROR: RPMB_INIT failed, shall not start listener services
04-09 21:57:45.592 10574 10574 V PhoneWindow: addContentView does not support content transitions
04-09 21:57:45.637  2464  2464 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{6f271de V.ED..... ......ID 0,0-1080,710 #1020026 android:id/keyboardView}
04-09 21:57:47.458 10574 10574 V PhoneWindow: addContentView does not support content transitions
04-09 21:57:47.512  2464  2464 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{6f271de V.ED..... ......ID 0,0-1080,710 #1020026 android:id/keyboardView}
04-09 21:57:48.534 10574 10574 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-09 21:57:48.537 10574 10574 E AndroidRuntime: FATAL EXCEPTION: main
04-09 21:57:48.537 10574 10574 E AndroidRuntime: Process: org.chromium.chrome, PID: 10574
04-09 21:57:48.537 10574 10574 E AndroidRuntime: java.lang.RuntimeException: Stub!
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.a.a.a.<init>(SslCertificate.java:16)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.pageinfo.CertificateViewer.addCertificateDetails(CertificateViewer.java:150)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.pageinfo.CertificateViewer.addCertificate(CertificateViewer.java:138)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.pageinfo.CertificateViewer.showCertificateChain(CertificateViewer.java:69)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.pageinfo.CertificateViewer.showCertificateChain(CertificateViewer.java:54)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.pageinfo.ConnectionInfoPopup.onClick(ConnectionInfoPopup.java:216)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.view.View.performClick(View.java:5204)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21153)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:53)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: Error reporting crash
04-09 21:57:48.537 10574 10574 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at org.chromium.chrome.browser.JavaExceptionReporter.uncaughtException(JavaExceptionReporter.java:33)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
04-09 21:57:48.537 10574 10574 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
04-09 21:57:48.537 10574 10574 I Process : Sending signal. PID: 10574 SIG: 9
04-09 21:57:48.570  1978  2287 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=20, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@6974535)
04-09 21:57:48.570  1978  7238 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=19, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@17ccdca)
04-09 21:57:48.570  1978  2165 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=20, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
04-09 21:57:48.570  1978  1988 D GraphicsStats: Buffer count: 5
04-09 21:57:48.571  1978  2165 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=20, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
04-09 21:57:48.571  1978  2165 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=19, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
04-09 21:57:48.571  1978  1988 I WindowState: WIN DEATH: Window{d135b3b u0 SurfaceView}
04-09 21:57:48.571  1978  2165 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=19, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
04-09 21:57:48.579  1978  2157 I WindowState: WIN DEATH: Window{d6c0808 u0 org.chromium.chrome/org.chromium.chrome.browser.ChromeTabbedActivity}
04-09 21:57:48.582  1978  1989 I WindowState: WIN DEATH: Window{bfa9b6c u0 org.chromium.chrome/org.chromium.chrome.browser.ChromeTabbedActivity}
04-09 21:57:48.592  1978  1996 W WindowAnimator: Failed to dispatch window animation state change.
04-09 21:57:48.592  1978  1996 W WindowAnimator: android.os.DeadObjectException
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStarted(IWindow.java:520)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:282)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-09 21:57:48.592  1978  1996 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-09 21:57:48.706  1978  7238 I ActivityManager: Process org.chromium.chrome (pid 10574) has died
04-09 21:57:48.707  1978  7238 W ActivityManager: Exception when unbinding service org.chromium.chrome/org.chromium.content.app.SandboxedProcessService1
04-09 21:57:48.707  1978  7238 W ActivityManager: android.os.DeadObjectException
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleUnbindService(ApplicationThreadNative.java:956)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:1874)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:2237)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:15570)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4594)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4757)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1325)
04-09 21:57:48.707  1978  7238 W ActivityManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
04-09 21:57:48.707   180   180 E lowmemorykiller: Error opening /proc/10606/oom_score_adj; errno=2
04-09 21:57:48.707   180   180 E lowmemorykiller: Error writing /proc/10713/oom_score_adj; errno=22
04-09 21:57:48.707   180   180 E lowmemorykiller: Error writing /proc/10635/oom_score_adj; errno=22
04-09 21:57:48.708   180   180 E lowmemorykiller: Error writing /proc/10635/oom_score_adj; errno=22
04-09 21:57:48.708  1978  7238 I ActivityManager: Killing 10713:org.chromium.chrome:sandboxed_process1/u0a51i15 (adj 10): isolated not needed
04-09 21:57:48.708  1978  7238 W libprocessgroup: failed to open /acct/uid_10051/pid_10713/cgroup.procs: No such file or directory
04-09 21:57:48.709  1978  7238 W ActivityManager: Exception when unbinding service org.chromium.chrome/org.chromium.content.app.PrivilegedProcessService0
04-09 21:57:48.709  1978  7238 W ActivityManager: android.os.DeadObjectException
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleUnbindService(ApplicationThreadNative.java:956)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:1874)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:2237)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:15570)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4594)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4757)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1325)
04-09 21:57:48.709  1978  7238 W ActivityManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
04-09 21:57:48.709   180   180 E lowmemorykiller: Error writing /proc/10635/oom_score_adj; errno=22
04-09 21:57:48.709   180   180 E lowmemorykiller: Error opening /proc/10606/oom_score_adj; errno=2
04-09 21:57:48.710  1978  7238 W ActivityManager: Exception when unbinding service org.chromium.chrome/org.chromium.content.app.SandboxedProcessService0
04-09 21:57:48.710  1978  7238 W ActivityManager: android.os.DeadObjectException
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleUnbindService(ApplicationThreadNative.java:956)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:1874)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:2237)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:15570)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4594)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4757)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1325)
04-09 21:57:48.710  1978  7238 W ActivityManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
04-09 21:57:48.710   180   180 E lowmemorykiller: Error opening /proc/10606/oom_score_adj; errno=2
04-09 21:57:48.710   180   180 E lowmemorykiller: Error writing /proc/10635/oom_score_adj; errno=22
04-09 21:57:48.710  1978  7238 W ActivityManager: Force removing ActivityRecord{7a4b869 u0 org.chromium.chrome/.browser.ChromeTabbedActivity t217}: app died, no saved state
04-09 21:57:48.714  1978  7238 I ActivityManager: Killing 10606:org.chromium.chrome:sandboxed_process0/u0a51i14 (adj 9): isolated not needed
04-09 21:57:48.714  1978  7238 W libprocessgroup: failed to open /acct/uid_10051/pid_10606/cgroup.procs: No such file or directory
04-09 21:57:48.716   180   180 E lowmemorykiller: Error writing /proc/10635/oom_score_adj; errno=22
04-09 21:57:48.724  1978  2157 I ActivityManager: Process org.chromium.chrome:privileged_process0 (pid 10635) has died
04-09 21:57:48.753  1978  1996 W WindowAnimator: Failed to dispatch window animation state change.
04-09 21:57:48.753  1978  1996 W WindowAnimator: android.os.DeadObjectException
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-09 21:57:48.753  1978  1996 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-09 21:57:48.762  1978  2289 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 10574 uid 10051
04-09 21:57:48.764  2464  2464 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{6f271de V.ED..... ......ID 0,0-1080,710 #1020026 android:id/keyboardView}
04-09 21:57:49.286  2522  2773 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-09 21:57:50.345  1978  2165 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 106] to 57
```

**Comment by thestinger** [comment] 2016-04-14 02:35
Does this still crash for you with the latest update? There's a new Chromium build. I expect that the problem is still unresolved but it might be fixed in the next major version. I think it must be an upstream issue.

**Comment by reenz0h** [comment] 2016-04-14 13:31
I'll try to test it once again. Also as [thestinger](https://github.com/thestinger) suggested on IRC, will try to install the app on stock (under emulator).

**Comment by reenz0h** [comment] 2016-04-14 18:05
Crash still occurs - tested on build **MMB29X.2016.04.10.03.35.03**

**Comment by thestinger** [comment] 2016-07-23 21:07
This is caused by not using the Chromium linker due to #202. I don't want to track upstream Chromium issues here. The only approach that will be taken here is fixing compatibility with the usual custom linker.

**Closed by thestinger** 2016-07-23 21:07 UTC
Labels: bug, upstream-app

**Comment by thestinger** [comment] 2016-07-23 22:57
Here's an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=630863/. It's the same problem as the other case.

**Comment by thestinger** [comment] 2016-07-24 12:16
Since #202 has been fixed, this problem will be avoided by using the Chromium linker again. The upstream bug is still present and I'd like to disable the Chromium linker again once it's resolved though.
