### ISSUE TITLE
WiFi disconnects on Nexus 5X

### ISSUE THREAD

**Issue by tobia** [copperhead/bugtracker#262] opened 2016-05-15 17:09 UTC
I'm experiencing regular WiFi disconnects when I start using the WiFi with significant traffic, if the OS has been running for some time. I regularly have to retry F-Droid downloads a few times before they succeed. It's not a network problem, as I have seen it happen on all WiFi networks I have used, which otherwise don't show any issue.

If the phone has been on for a few days and I start a really big and fast download, such as downloading a popular YouTube video in HD with SnapTube (on a regular 10Mbit DSL, nothing fancy) **the whole OS freezes.** Rebooting solves the problem, at least for a while.

This bug is quite troublesome.

I have the latest OTA update on a Nexus 5X, no root or other customization of any sort.

**Comment by polyzen** [comment] 2016-05-15 21:08
Related to #134?

**Comment by tobia** [comment] 2016-05-15 21:19
I don't think so. It's not a problem of the WiFi going away when the phone is put to sleep. Here something is definitely crashing and closing the active connections when the WiFi is being used for a big transfer. Most of the times it just crashes the WiFi and I can disable / enable it from the top drawer; but sometimes it brings down the entire OS. Moreover, this is 5X, while #134 was about the 5.

**Comment by polyzen** [comment] 2016-05-15 21:29
The original poster for the [upstream issue](https://code.google.com/p/android/issues/detail?id=190667) for #134 had a Nexus 6, and I saw at least one other device in the thread. ¯\\_(ツ)_/¯

**Comment by tobia** [comment] 2016-05-15 22:08
I have enabled WiFi Verbose Logging and will update with more info as soon as I can figure out whether this has been reported upstream or not.

**Comment by thestinger** [comment] 2016-05-15 23:23
There is no kernel hardening for the 5X yet, so any issues with WiFi are upstream ones unless they are somehow caused by scanning MAC randomization.

**Comment by tobia** [comment] 2016-05-15 23:58
As I mentioned in #147, this phone's wifi is so bad that I'm returning it to the store.

I suggest you take it out of the recommended devices in the project's homepage, or at least put an asterisk and a comment there.

**Comment by thestinger** [comment] 2016-05-16 00:08
It's one of the two modern phones that CopperheadOS supports and there are more severe Android bugs than stuff like this. I'm interested in fixing or working around any issues that are triggered or at least made more frequent by CopperheadOS features but I'm not just going to abandon the 5X because there's a bug. Even though there are upstream reports for issues like this, it's possible that scanning MAC randomization is a trigger for it. Other people might be running into it more rarely or not at all. I expect that if the signal drops off, scanning MAC randomization kicks in, and there might be some chance that it breaks. The symptoms are the same as the breakage that was caused by full MAC randomization, which makes me think that it's likely. It's strange that it doesn't break more reliably though.

**Comment by thestinger** [comment] 2016-05-16 00:19
I filed #269 about the potential of issues with scanning MAC randomization on the 5X. I'll make a build without scanning MAC randomization for the 5X to test this. I can publish it for testing outside of the regular update channel.

**Comment by tobia** [comment] 2016-05-16 00:25
Thanks. I'm willing to test it before I return my device. Will it be signed? Otherwise it would force me to erase my phone (IIUC) which would certainly change my network usage patterns.

**Comment by thestinger** [comment] 2016-05-16 00:28
Yes, it will be signed so it can be sideloaded. It's probably necessary to reset network settings to make the change kick in though since scanning MAC randomization is enabled via Android's template wpa_supplicant configuration which it doesn't actually update. If it ends up being the cause then the removal of this configuration line can be scripted as part of an upgrade and then when the issue is resolved it will need to be scripted to add it back for existing devices.

**Comment by thestinger** [comment] 2016-05-16 03:16
Here the over-the-air update: https://paste.xinu.at/trHKFZ/. Need to use Settings -> Backup and reset -> Network setting reset after installing to clear the old settings where scanning MAC randomization is enabled after installing the update.

**Comment by thestinger** [comment] 2016-05-16 03:18
I think it's likely that this "fixes" the problem by making the need to toggle WiFi off and on again much less common. The underlying issue is still there and can happen, but it's probably very rare.

**Comment by thestinger** [comment] 2016-05-16 09:17
MAC randomization for scanning appears to be the trigger for the issue. The change will be included in the next release. I expect that the YouTube / SnapTube issue is unrelated and will be still be present though.

**Comment by thestinger** [comment] 2016-05-16 09:18
(should file it in a new bug though since this was all about the WiFi disconnect issue)

**Comment by thestinger** [comment] 2016-05-16 09:22
A Google employee seems interested in working on this, so we'll see what happens. It could be unfixable if it's hardware or firmware issue though, and even fixing the driver could be very difficult.

**Comment by tobia** [comment] 2016-05-16 09:38
> I expect that the YouTube / SnapTube issue is unrelated and will be still be present though.
> (should file it in a new bug though since this was all about the WiFi disconnect issue)

This issue is about the WiFi disconnect issue happening when the WiFi is used heavily. Youtube was just an example, but downloading the OTA updates or any other large file would also trigger the disconnect that this issue is about.

I will try the update and let you know in a few days, because soon after booting the problem does not appear.

**Comment by thestinger** [comment] 2016-05-16 09:49
Ah then it's different from the issue I was aware of already, but it might be the same.

**Comment by thestinger** [comment] 2016-05-19 04:28
Have been testing this and I'm convinced it isn't a problem anymore. Dropping MAC randomization completely for the 5X appears to have resolved any additional WiFi stability issues in CopperheadOS compared to stock. The occasional remaining issues are in line with the confirmed upstream bugs.

**Closed by thestinger** 2016-05-19 04:28 UTC
Labels: bug, upstream, workaround in place

**Comment by tobia** [comment] 2016-05-19 10:24
I agree. The image you provided seems to have solved all of the stability bugs when actually using the WiFi. The idle / sleeping / wakeup bugs are still there, but they are not due to CopperheadOS.
