### ISSUE TITLE
Cannot upgrade F-Droid to 0.101 from 0.100.1 

### ISSUE THREAD

**Issue by BytesTuner** [copperhead/bugtracker#467] opened 2016-10-04 23:07 UTC
I got the following notification when I'm trying to install the newest version of F-Droid (0.101):

"The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first. Please do this and try again. (Note that uninstalling will erase any internal data stored by the application)."

I have tried 2 different ways to uninstall the old versions (0.100.1) but it's like the version installed by default cannot be uninstalled...is it the case? If yes, is there a workaround way to do this so I will be able to upgrade F-Droid?

Thank you!

**Comment by thestinger** [comment] 2016-10-04 23:08
It's working as intended. The new version of F-Droid will be included in the next update.

**Closed by thestinger** 2016-10-04 23:08 UTC
