### ISSUE TITLE
Cannot edit apn

### ISSUE THREAD

**Issue by mikewizowski** [copperhead/bugtracker#417] opened 2016-09-04 22:02 UTC
I am unable to use cellular data for any carrier here in the USA. I have tried every fix I know o as well as multiple sims. The phone says APN settings not available to this user. Prl update and auto config. Auto config hangs and doesn't work. Will post logs if need be. Other aosp ROMs work fine, sim is brand new

**Comment by thestinger** [comment] 2016-09-04 22:07
I doubt this is a CopperheadOS issue. Have you tried standard workarounds for this AOSP issue?

https://android.stackexchange.com/questions/120707/how-to-solve-the-apn-settings-are-not-available-for-this-user-issue

**Comment by mikewizowski** [comment] 2016-09-04 22:10
I will attempt again I followed the standard guide from XDA

**Comment by thestinger** [comment] 2016-09-04 22:17
Maybe there's something useful in `adb logcat`.

**Comment by mikewizowski** [comment] 2016-09-05 01:15
It appears it may be tied to sprint DM bug that was reported earlier i am able to access data through *#*#3282#*#* but data does not work

**Comment by mikewizowski** [comment] 2016-09-05 01:17
Correction * # * # 3282 # * # * remove spaces as needed

**Comment by mikewizowski** [comment] 2016-09-05 01:18
I will root the rom and try uninstalling dmservice apk and installing version from the previous thread

**Comment by mikewizowski** [comment] 2016-09-05 01:37
hmm it appears the data issue is something in the base code with copperhead os perhaps a fix like the one used on chroma rom would fix the issue I am not a programmer so this is all beyond me i will be willing to test new builds for possible fixes

**Comment by thestinger** [comment] 2016-09-05 01:50
We can't work on this because we don't have access to these carriers. I also don't know what fix you think we should apply. I never saw a link to that.

**Comment by mikewizowski** [comment] 2016-09-05 02:31
Its on the sprint dm bug poated earlier there is a link part of the way down to an apk file for the sprint dm manager

**Comment by thestinger** [comment] 2016-09-05 09:36
We're not going to use a binary from an unknown source.

**Comment by thestinger** [comment] 2016-09-05 09:36
It seems this is the known SprintDM issue, which is caused by Google not doing binary releases anymore. It's not something we're interested in working around ourselves. If it's fixed in android-prepare-vendor, it will be fixed in CopperheadOS.

**Closed by thestinger** 2016-09-05 09:36 UTC
Labels: bug, upstream

**Comment by thestinger** [comment] 2016-09-06 09:12
SprintDM is no longer present in the Nougat-based builds, since there isn't currently a method of including these apps. Any carrier functionality depending on this stuff is simply not supported anymore due to Google not producing binary releases.
