### ISSUE TITLE
Close all open apps

### ISSUE THREAD

**Issue by tobia** [copperhead/bugtracker#268] opened 2016-05-15 18:44 UTC
A button to close all open apps (screens) is a common customization added to the AOSP base image. It's usually added somewhere to the recent screen list (🞏)

Edit: I'll only leave the **privacy** argument here: if someone asks to use my phone, I'd like to be able to quickly clear the recent screen list and close all open apps, resetting them to their default state (e.g. closing open emails, open conversations...) so that they don't tap on 🞏 by mistake and read a conversation I was having with someone else.

**Comment by polyzen** [comment] 2016-05-15 21:02
Duplicate of #171.

**Comment by tobia** [comment] 2016-05-15 21:26
Sorry, didn't see that one. At least I'm making a privacy argument here :-)

**Comment by thestinger** [comment] 2016-05-15 23:26
Use the guest account. It takes a second to switch to it via the user icon in the notification drawer.

**Closed by thestinger** 2016-05-15 23:26 UTC
Labels: enhancement, unconfirmed
