### ISSUE TITLE
ChatSecure can't connect through Orbot

### ISSUE THREAD

**Issue by nexus4fun** [copperhead/bugtracker#197] opened 2016-03-10 21:19 UTC
Hello, seems that Orbot + Chatsecure isn't working only on Cooperhead OS. The ChatSecure bug for Android 6.0 was fixed in version 14.2.3. I have AOSP Rom on my Moto G (Android 6.0.1) and Orbot + ChatSecure is working without any issues. On Cooperhead OS, seems that ChatSecure can't find Orbot, as it always show "Orbot doesn't appear to be runing.." I really like the work you are doing, but is there any possibility to fix this issue? If you need any more information about this issue, pleas say me what i must do :) as i am begginer...

**Comment by thestinger** [comment] 2016-03-10 21:34
Which device are you using for CopperheadOS?

I suspect this is caused by `hidepid=2` which is also going to be enabled in Android N.

**Comment by lagosazules** [comment] 2016-03-11 07:15
I got exactly the same problem on Nexus 5

**Comment by thestinger** [comment] 2016-03-11 14:08
It needs to be confirmed that this doesn't also occur on the Android N preview builds. If it does, then it's simply caused by `hidepid=2` and is an upstream bug in the apps since stock Android will be following CopperheadOS's lead on this.

**Comment by lagosazules** [comment] 2016-03-11 18:00
I Can't find  a Nexus 5 android N  preview on devolper.android.com/download, no N for the 5 anymore?

**Comment by thestinger** [comment] 2016-03-11 18:05
No preview doesn't mean they won't support it in the official release. There's a good chance it will only get Marshmallow security updates from this point onwards though.

**Comment by marix11** [comment] 2016-03-11 18:18
Another client working good with orbot

**Comment by lagosazules** [comment] 2016-03-11 18:33
Frdoid or Orfox working ok with Orbot  but try to add a new or secret identity account in Chatsecure and it ask you to start Orbo, following bij a crash

**Comment by thestinger** [comment] 2016-03-11 18:35
Going to need more information than that including logs from `adb logcat`.

**Comment by thestinger** [comment] 2016-03-11 19:13
And if you're on the Nexus 5 you should try enabling PaX soft mode in developer settings whenever you run into problems with apps. The PaX userspace features don't support 64-bit ARM so that doesn't apply to the other devices yet.

**Comment by lagosazules** [comment] 2016-03-11 19:31
Enabling or disable PaX soft mode, no result , i like to log but didn't fount out jet how to do this

**Comment by darknetj** [comment] 2016-03-11 19:41
@lagosazules follow the guidelines for proper bug reporting here https://github.com/copperhead/bugtracker#reporting-issues

**Comment by vanitasvitae** [comment] 2016-03-14 18:20
Short question: Android Studio cannot find debuggable apps when I'm programming. Is this also caused by the hidepid flag?

**Comment by thestinger** [comment] 2016-03-14 19:42
I doubt it has to do with hidepid. It was upstreamed, and I don't think we're missing any of the exceptions that are upstream.

It's not a userdebug build so that might not be supposed to work. You would need to find out if it's supposed to work on user builds before it could be considered as a bug. Having more kinds of builds isn't going to happen without significant funding.

**Comment by nexus4fun** [comment] 2016-03-15 10:17
Hello, i have a Nexus 5 phone. Runing latest Cooperhead OS version. Orbot, ChatSecure and Orfox is latest versions downloaded from F-Droid. I logged two situations. Orbot + Orfox and Orbot + ChatSecure. Both cases Orbot was not running when i started Orfox or ChatSecure. Orfox launched Orbot itself and was working without any issues (just one thing i notcied is, when i select in Orbot "Use Default Iptables" than Orfox doesn't connect). ChatSecure i launched and tried to create "Burner account", got warning that Orbot isn't runing, i choosed to start it. I attached logs of both cases.

[Log Chatsecure.txt](https://github.com/copperhead/bugtracker/files/173653/Log.Chatsecure.txt)
[Log Orfox.txt](https://github.com/copperhead/bugtracker/files/173655/Log.Orfox.txt)

**Comment by thestinger** [comment] 2016-03-15 16:00
This is an upstream issue in OnionKit. It will also occur on stock Android N because `hidepid=2` landed upstream. I don't think I should implement a workaround because it's also going to be broken on stock. It needs to be addressed in OnionKit instead. Ideally, Orbot would expose an IPC API for checking if it is running rather than relying on functionality that's not guaranteed to be there even with stock Android.

**Closed by thestinger** 2016-03-15 16:00 UTC
Labels: bug, upstream-app

**Comment by n8fr8** [comment] 2016-03-15 17:48
We have fixed this in NetCipher, as it now uses an Intent API to query for status of Orbot. We will work to update ChatSecure as soon as we can to use this. In the meantime, you can use the Orbot VPN feature and just select ChatSecure in the Orbot settings transproxy app list, as one alternative solution.

**Comment by thestinger** [comment] 2016-03-15 18:46
@n8fr8 Thanks! I assumed this was the same issue you mentioned on Twitter but I wasn't sure.

**Comment by lagosazules** [comment] 2016-05-09 07:32
@n8fr8 
Still no ETA for a update?
 "We have fixed this in NetCipher, as it now uses an Intent API to query for status of Orbot. We will work to update ChatSecure as soon as we can to use this"

This is not working on a non rooted CopperheadOS:
"In the meantime, you can use the Orbot VPN feature and just select ChatSecure in the Orbot settings transproxy app list, as one alternative solution."

Thanks in advance , I prefer Chatsecure above Conversations, Zom or Xabber

**Comment by vanitasvitae** [comment] 2016-05-09 07:38
@lagosazules It is fixed, but you cannot use isOrbotRunning. Apps have to check for running Orbot via Intent and BroadcastReceiver now.

**Comment by lagosazules** [comment] 2016-05-09 14:06
Thanks for the fast answer, bus using a Nexus 5 with latest CopperheadOS MOB30J.2016.05.08.05.30.34, latest Chatsecure 14.2.3 and Orbot 15.1.2 still this restricions:
- Can't make a burner "Secret Identity" (Orbot doesn't apear to be running)
- Can't make a "New account" using the option "Connect via Tor" (Orbot doesn't apear to be running)
without Orbot yes you can make a new account.

security level low and disable Pax make now difrence 

Great combinacion Chatsecure, Orbot and CopperheadOS, hope to get it full working.

**Comment by n8fr8** [comment] 2016-05-09 14:08
We have not yet released our update of ChatSecure with the new Orbot API to make this work. This is on my medium priority list, and I'll try to get it done this week.

**Comment by lagosazules** [comment] 2016-05-09 14:12
perfect, thanks for the great work you are doing
